### ISSUE TITLE
Character Sheets don't Open - Foundry v9

### ISSUE THREAD

**Issue by crlong02** [jsavko/foundryvtt-quest#1]
I just updated to Foundry v9 and wanted to try the Quest system.  After creating an Actor, I click on it to open the sheet and nothing happens.  Not sure if this is happening in versions of Foundry earlier than 9.

**Comment by jsavko** [comment]
Press f12 and see if any errors are in the console.  I’m traveling for the holiday and won’t be able to do any specific troubleshooting, but I may be able to tell what the issue is from that error

**Comment by crlong02** [comment]
Tons of errors.  I'll try to screen shot them all for you.

I am on v9.

![Error1](https://user-images.githubusercontent.com/46548183/147000645-76920b99-66fc-47a0-95f1-61e127c630b9.JPG)
![Error2](https://user-images.githubusercontent.com/46548183/147000646-777a1cf7-1c1f-435b-b76a-a5721dc3b232.JPG)
![Error3](https://user-images.githubusercontent.com/46548183/147000647-c1e3d37d-bc4a-4df3-9183-ec7e65efabac.JPG)
![Error4](https://user-images.githubusercontent.com/46548183/147000650-aaf50407-4c2b-418d-ac63-aea2d9fadcd1.JPG)
![Error5](https://user-images.githubusercontent.com/46548183/147000637-79d62b92-efa8-4ea3-b12c-e90cf231b567.JPG)
![Error6](https://user-images.githubusercontent.com/46548183/147000639-c0e355e2-a742-4c17-8a68-dbdcb43e91a2.JPG)
![Error7](https://user-images.githubusercontent.com/46548183/147000640-0e1f9299-6704-4077-b836-8f739c048af9.JPG)
![Error8](https://user-images.githubusercontent.com/46548183/147000641-d8b9f5c7-c452-4b62-8ee4-5a53d874983c.JPG)
![Error9](https://user-images.githubusercontent.com/46548183/147000644-b75fda2d-23dd-4e38-bafc-c966af70a205.JPG)

**Comment by crlong02** [comment]
Some are other modules causing issues, but you can clearly see the Actor sheet issue.

**Comment by jsavko** [comment]
Oh I know exactly what the problem is.  I changed the package name because it was conflicting with another package and didn’t update the absolute paths.  It will be a few days before I can fix it

**Comment by jsavko** [comment]
I pushed an update directly into the repo from my phone that should fix the issue. Just remove and reinstall the system and it should update the files.  It wont show up as a new version as I am only mobile for the next few days

**Comment by crlong02** [comment]
That's amazing.  Completely worked!  But you should have waited until you were back from holiday!  Thank you, though!
