### ISSUE TITLE
The compendium doesn't have long description of abilities

### ISSUE THREAD

**Issue by Marcloure** [jsavko/foundryvtt-quest#18]
Abilities in the Compendium have only their short description written. As far as I saw, none of them have their long descriptions.

**Comment by jsavko** [comment]
We don't have a license to distribute the long descriptions which is why there are none

**Comment by Marcloure** [comment]
Aren't the rules available for free? Anyway, that is fine then.

**Comment by jsavko** [comment]
They are, but they aren't free for anyone to distribute.  I've already had a conversation with the publisher/author and they wouldn't grant a distribution license

**Comment by Marcloure** [comment]
I see. That is a shame, but alas. Thanks for the info!
