### ISSUE TITLE
Issues reported by FoundryVTT v10 build 291

### ISSUE THREAD

**Issue by JesseHawkins** [jsavko/foundryvtt-quest#19]
[foundryvtt-quest] The system "foundryvtt-quest" is using "name" which is deprecated in favor of "id"
[foundryvtt-quest] The system "foundryvtt-quest" is using "author" which is deprecated in favor of "authors"
[foundryvtt-quest] The system "foundryvtt-quest" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

If I were a coder I'd make these changes myself and submit them for your approval. As it stands, someone else will have to make the fix.

**Comment by JesseHawkins** [comment]
Any plans to update it?

**Comment by jsavko** [comment]
I am about 1/2 done up the update, but I haven't had time to work on it.  I hope to get it done in the next month or so, but things keep coming up.   I'm not currently running any games in Quest which also makes it slower
